version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database 
    env_file:
      - .env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: store
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
      pgdata: